const mongoose = require('mongoose');
const dotenv = require('dotenv');
const path = require('path');
const Product = require('../models/Product');
const Industry = require('../models/Industry');

dotenv.config({ path: path.join(__dirname, '../.env') });

// ─── Verified Unsplash photo IDs with auto=format&fit=crop for reliability ──
const industries = [
  {
    name: 'Food & Beverage',
    slug: 'food-beverage',
    description: 'Custom packaging for food brands, bakeries, restaurants, and beverage companies. FDA-compliant materials available.',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&h=500&q=80',
    featured: true,
  },
  {
    name: 'Cosmetics & Beauty',
    slug: 'cosmetics-beauty',
    description: 'Luxury packaging for skincare, makeup, and wellness brands. Premium finishes and sustainable options.',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&h=500&q=80',
    featured: true,
  },
  {
    name: 'E-Commerce',
    slug: 'ecommerce',
    description: 'Durable, branded shipping boxes for online retailers. Custom inserts, void fill, and unboxing experiences.',
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=800&h=500&q=80',
    featured: true,
  },
  {
    name: 'Apparel & Fashion',
    slug: 'apparel-fashion',
    description: 'Custom boxes, bags, and tissue wrapping for clothing, shoes, and accessories brands.',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&h=500&q=80',
    featured: false,
  },
  {
    name: 'Electronics',
    slug: 'electronics',
    description: 'ESD-safe, protective packaging for gadgets, components, and consumer electronics.',
    image: 'https://images.unsplash.com/photo-1468495244123-6c6c332eeece?auto=format&fit=crop&w=800&h=500&q=80',
    featured: false,
  },
  {
    name: 'Cannabis & CBD',
    slug: 'cannabis-cbd',
    description: 'Child-resistant, compliant packaging for cannabis and CBD products with custom branding.',
    image: 'https://images.unsplash.com/photo-1593476550610-87baa860004a?auto=format&fit=crop&w=800&h=500&q=80',
    featured: false,
  },
  {
    name: 'Pharmaceuticals',
    slug: 'pharmaceuticals',
    description: 'Tamper-evident, GMP-compliant pharmaceutical packaging for medicines and supplements.',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&h=500&q=80',
    featured: false,
  },
  {
    name: 'Luxury Goods',
    slug: 'luxury-goods',
    description: 'High-end rigid boxes, magnetic closures, and premium finishes for luxury products.',
    image: 'https://images.unsplash.com/photo-1611085583191-a3b181a88401?auto=format&fit=crop&w=800&h=500&q=80',
    featured: true,
  },
  {
    name: 'Subscription Boxes',
    slug: 'subscription-boxes',
    description: 'Eye-catching monthly subscription boxes designed to delight customers on every delivery.',
    image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=800&h=500&q=80',
    featured: false,
  },
  {
    name: 'Retail & POS',
    slug: 'retail-pos',
    description: 'Shelf-ready retail packaging, display boxes, and point-of-sale units for brick-and-mortar.',
    image: 'https://images.unsplash.com/photo-1506617564039-2f3b650b7010?auto=format&fit=crop&w=800&h=500&q=80',
    featured: false,
  },
  {
    name: 'Healthcare',
    slug: 'healthcare',
    description: 'Sterile, medical-grade packaging for healthcare devices, kits, and personal protective equipment.',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&h=500&q=80',
    featured: false,
  },
  {
    name: 'Toys & Games',
    slug: 'toys-games',
    description: 'Bright, durable packaging for toys, board games, and hobby products. Safe, child-friendly materials.',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&h=500&q=80',
    featured: false,
  },
  {
    name: 'Pet Products',
    slug: 'pet-products',
    description: 'Fun, sturdy packaging for pet food, treats, and accessories. Available in eco-friendly options.',
    image: 'https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?auto=format&fit=crop&w=800&h=500&q=80',
    featured: false,
  },
  {
    name: 'Automotive',
    slug: 'automotive',
    description: 'Heavy-duty industrial packaging for auto parts, accessories, and aftermarket products.',
    image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=800&h=500&q=80',
    featured: false,
  },
  {
    name: 'Gift & Specialty',
    slug: 'gift-specialty',
    description: 'Beautiful gift boxes, hamper packaging, and ribbon-ready specialty boxes for every occasion.',
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&h=500&q=80',
    featured: true,
  },
];

// ─── 15 Products — each with a unique, verified Unsplash image ─────────────────
const products = [
  {
    name: 'Classic Mailer Box',
    slug: 'classic-mailer-box',
    category: 'Mailer Boxes',
    description: 'The most popular choice for e-commerce brands. Self-locking, no glue needed, ultra-clean unboxing experience.',
    price: 1.20,
    boxType: 'Mailer Box',
    material: 'E-Flute Corrugated',
    finish: 'Matte Lamination',
    dimensions: { length: '20-40', width: '15-30', height: '5-20' },
    minOrderQty: 50,
    addons: ['Custom Insert', 'Tissue Paper', 'Sticker Sheet'],
    featured: true,
    image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=800&h=500&q=80',
  },
  {
    name: 'Rigid Gift Box',
    slug: 'rigid-gift-box',
    category: 'Rigid Boxes',
    description: 'Premium rigid box with magnetic closure. Perfect for luxury goods, gifts, and high-end retail.',
    price: 3.80,
    boxType: 'Rigid Box',
    material: 'Grey Board 2mm',
    finish: 'Gloss UV Coating',
    dimensions: { length: '15-35', width: '10-25', height: '5-15' },
    minOrderQty: 25,
    addons: ['Magnetic Closure', 'Ribbon Pull', 'Foam Insert'],
    featured: true,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&h=500&q=80',
  },
  {
    name: 'Kraft Tuck Box',
    slug: 'kraft-tuck-box',
    category: 'Folding Cartons',
    description: 'Eco-friendly kraft tuck-end box. Ideal for bakeries, food, candles, and soap brands.',
    price: 0.65,
    boxType: 'Tuck End Box',
    material: 'Kraft Paper 350gsm',
    finish: 'Uncoated Natural',
    dimensions: { length: '5-25', width: '5-20', height: '3-15' },
    minOrderQty: 100,
    addons: ['Window Cutout', 'Spot UV', 'Embossing'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&h=500&q=80',
  },
  {
    name: 'Cosmetic Sleeve Box',
    slug: 'cosmetic-sleeve-box',
    category: 'Sleeve Boxes',
    description: 'Two-piece slide-out sleeve box with a premium feel. Popular for skincare sets and cosmetics.',
    price: 2.10,
    boxType: 'Sleeve Box',
    material: 'Coated Artboard 400gsm',
    finish: 'Soft Touch Lamination',
    dimensions: { length: '10-30', width: '8-20', height: '3-12' },
    minOrderQty: 50,
    addons: ['Hot Foil Stamping', 'Embossing', 'Ribbon'],
    featured: true,
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&h=500&q=80',
  },
  {
    name: 'Corrugated Shipping Box',
    slug: 'corrugated-shipping-box',
    category: 'Shipping Boxes',
    description: 'Heavy-duty corrugated RSC box for safe shipping. BCT-tested for stacking strength.',
    price: 0.95,
    boxType: 'RSC Shipping Box',
    material: 'B-Flute Corrugated',
    finish: 'Uncoated',
    dimensions: { length: '20-60', width: '15-50', height: '10-40' },
    minOrderQty: 50,
    addons: ['Fragile Label', 'Custom Interior Print', 'Handles'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1616401784845-180882ba9ba8?auto=format&fit=crop&w=800&h=500&q=80',
  },
  {
    name: 'Window Display Box',
    slug: 'window-display-box',
    category: 'Retail Boxes',
    description: 'Folding carton with clear PET window. Perfect for retail shelf display of food, toys, and cosmetics.',
    price: 1.45,
    boxType: 'Window Box',
    material: 'SBS Artboard 350gsm',
    finish: 'Gloss Lamination',
    dimensions: { length: '8-28', width: '6-22', height: '4-18' },
    minOrderQty: 100,
    addons: ['PET Window', 'Hanger Tab', 'Spot UV'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1567958451986-2de427a4a0be?auto=format&fit=crop&w=800&h=500&q=80',
  },
  {
    name: 'Luxury Drawer Box',
    slug: 'luxury-drawer-box',
    category: 'Rigid Boxes',
    description: 'Elegant rigid drawer box with linen texture. The gold standard for jewelry, watches, and perfumes.',
    price: 5.50,
    boxType: 'Drawer Box',
    material: 'Linen-Wrapped Rigid',
    finish: 'Linen Texture + Foil',
    dimensions: { length: '8-25', width: '6-20', height: '3-10' },
    minOrderQty: 25,
    addons: ['Gold Foil', 'Velvet Insert', 'Logo Deboss'],
    featured: true,
    image: 'https://images.unsplash.com/photo-1611085583191-a3b181a88401?auto=format&fit=crop&w=800&h=500&q=80',
  },
  {
    name: 'Gable Top Box',
    slug: 'gable-top-box',
    category: 'Specialty Boxes',
    description: 'Charming gable box with built-in handle. A favourite for party favours, bakeries, and gift packaging.',
    price: 0.85,
    boxType: 'Gable Box',
    material: 'SBS Artboard 300gsm',
    finish: 'Matte Lamination',
    dimensions: { length: '10-25', width: '8-18', height: '12-28' },
    minOrderQty: 100,
    addons: ['Window', 'Custom Tag', 'Tissue Paper'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&h=500&q=80',
  },
  {
    name: 'Pizza Kraft Box',
    slug: 'pizza-kraft-box',
    category: 'Food Boxes',
    description: 'Grease-resistant kraft pizza box with full-colour lid print. FDA-compliant food-safe lining.',
    price: 0.75,
    boxType: 'Pizza Box',
    material: 'Kraft Corrugated',
    finish: 'Food-Safe Coating',
    dimensions: { length: '20-45', width: '20-45', height: '4-8' },
    minOrderQty: 100,
    addons: ['Logo Print', 'QR Code', 'Recycled Material'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&h=500&q=80',
  },
  {
    name: 'Subscription Mystery Box',
    slug: 'subscription-mystery-box',
    category: 'Mailer Boxes',
    description: 'Thick, premium mailer box with interior full-colour print. Designed for memorable unboxing moments.',
    price: 2.40,
    boxType: 'Mailer Box',
    material: 'B-Flute Corrugated',
    finish: 'Matte + Spot UV',
    dimensions: { length: '25-45', width: '20-35', height: '10-25' },
    minOrderQty: 50,
    addons: ['Interior Print', 'Perforated Tear Strip', 'QR Code'],
    featured: true,
    image: 'https://images.unsplash.com/photo-1512909006721-3d6018887383?auto=format&fit=crop&w=800&h=500&q=80',
  },
  {
    name: 'Hang Tag Retail Box',
    slug: 'hang-tag-box',
    category: 'Retail Boxes',
    description: 'Header card box with Euro-slot hang tag. Ready for peg hooks in retail and pharmacy chains.',
    price: 0.90,
    boxType: 'Header Box',
    material: 'Coated Artboard 350gsm',
    finish: 'Gloss Lamination',
    dimensions: { length: '6-20', width: '4-15', height: '2-10' },
    minOrderQty: 200,
    addons: ['Euro Slot', 'Barcode Panel', 'Tear Strip'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=800&h=500&q=80',
  },
  {
    name: 'Cannabis Compliance Box',
    slug: 'cannabis-compliance-box',
    category: 'Specialty Boxes',
    description: 'Child-resistant, tamper-evident packaging for cannabis flower, edibles, and CBD products.',
    price: 1.80,
    boxType: 'CR Tuck Box',
    material: 'SBS Artboard 400gsm',
    finish: 'Soft Touch + Spot UV',
    dimensions: { length: '6-18', width: '4-12', height: '2-8' },
    minOrderQty: 100,
    addons: ['Child Lock', 'Tamper Seal', 'Lab Results Panel'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1593476550610-87baa860004a?auto=format&fit=crop&w=800&h=500&q=80',
  },
  {
    name: 'Eco Kraft Mailer',
    slug: 'eco-kraft-mailer',
    category: 'Mailer Boxes',
    description: '100% recycled content corrugated mailer. FSC-certified and fully compostable. Zero plastic used.',
    price: 1.05,
    boxType: 'Eco Mailer',
    material: '100% Recycled Corrugated',
    finish: 'Uncoated Kraft',
    dimensions: { length: '15-40', width: '12-30', height: '4-18' },
    minOrderQty: 50,
    addons: ['Compostable Label', 'Soy Ink Print', 'Seed Paper Insert'],
    featured: true,
    image: 'https://images.unsplash.com/photo-1580828343064-fde4fc206bc6?auto=format&fit=crop&w=800&h=500&q=80',
  },
  {
    name: 'Apparel Tissue Wrap Box',
    slug: 'apparel-tissue-box',
    category: 'Apparel Boxes',
    description: 'Flat-pack collapsible box for clothing and apparel. Comes with branded tissue paper and sticker seal.',
    price: 1.60,
    boxType: 'Collapsible Box',
    material: 'Coated Grey Board',
    finish: 'Matte Lamination',
    dimensions: { length: '20-50', width: '15-40', height: '3-10' },
    minOrderQty: 50,
    addons: ['Tissue Paper', 'Logo Sticker', 'Ribbon'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=800&h=500&q=80',
  },
  {
    name: 'Rigid Neck Box',
    slug: 'rigid-neck-box',
    category: 'Rigid Boxes',
    description: 'Two-piece rigid neck and shoulder box. Popular for premium electronics, candles, and spirits.',
    price: 4.20,
    boxType: 'Neck Box',
    material: 'Grey Board 2.5mm',
    finish: 'Gloss UV + Foil',
    dimensions: { length: '10-30', width: '8-25', height: '5-18' },
    minOrderQty: 25,
    addons: ['Foil Stamping', 'Foam Insert', 'Magnetic Closure'],
    featured: true,
    image: 'https://images.unsplash.com/photo-1560343090-f0409e92791a?auto=format&fit=crop&w=800&h=500&q=80',
  },
];

async function seed() {
  try {
    console.log('🔌 Connecting to MongoDB…');
    await mongoose.connect(process.env.MONGODB_URI);

    console.log('🗑  Clearing old industries & products…');
    await Industry.deleteMany({});
    await Product.deleteMany({});

    console.log('🌱 Seeding 15 industries…');
    await Industry.insertMany(industries);

    console.log('🌱 Seeding 15 products…');
    await Product.insertMany(products);

    console.log('✅ Seed complete — 15 industries + 15 products with verified images.');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seeding failed:', err);
    process.exit(1);
  }
}

seed();
